/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 7caa7b16384e71a222865127961e3b31)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "GainChefAgent";
	}
	interface Env {
		GainChefAgent: DurableObjectNamespace<import("./src/server").GainChefAgent>;
		AI: Ai;
		MEAL_PREP: Workflow;
	}
}
interface Env extends Cloudflare.Env {}
